# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
    - "helium-diy/lightweight-dashboard:{{ .Tag }}"
    - "helium-diy/lightweight-dashboard:v{{ .Major }}"
    - "helium-diy/lightweight-dashboard:v{{ .Major }}.{{ .Minor }}"
    - "helium-diy/lightweight-dashboard:latest"
    - "gcr.io/helium-diy/lightweight-dashboard:{{ .Tag }}"
    - "gcr.io/helium-diy/lightweight-dashboard:v{{ .Major }}"
    - "gcr.io/helium-diy/lightweight-dashboard:v{{ .Major }}.{{ .Minor }}"
    - "gcr.io/helium-diy/lightweight-dashboard:latest"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/amd64"
  -
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
    - "helium-diy/lightweight-dashboard:{{ .Tag }}"
    - "helium-diy/lightweight-dashboard:v{{ .Major }}"
    - "helium-diy/lightweight-dashboard:v{{ .Major }}.{{ .Minor }}"
    - "helium-diy/lightweight-dashboard:latest"
    - "gcr.io/helium-diy/lightweight-dashboard:{{ .Tag }}"
    - "gcr.io/helium-diy/lightweight-dashboard:v{{ .Major }}"
    - "gcr.io/helium-diy/lightweight-dashboard:v{{ .Major }}.{{ .Minor }}"
    - "gcr.io/helium-diy/lightweight-dashboard:latest"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/arm64"