# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: lightweight-dashboard
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - arm64
    - amd64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: false

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

  # You can change the name of the GitHub release.
  # Default is `{{.Tag}}`
  name_template: "{{.ProjectName}}-v{{.Version}}"
checksum:
  name_template: 'checksums.txt'
source:
  enabled: true
sboms:
  - artifacts: archive
  - id: source # Two different sbom configurations need two different IDs
    artifacts: source
signs:
- cmd: cosign
  env:
  - COSIGN_EXPERIMENTAL=1
  certificate: '${artifact}.pem'
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
  artifacts: checksum
  output: true

dockers:
  -
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
    - "ghcr.io/heliumdiy/lightweight-dashboard:v{{ .Tag }}-amd64"
    - "ghcr.io/heliumdiy/lightweight-dashboard:v{{ .Major }}-amd64"
    - "ghcr.io/heliumdiy/lightweight-dashboard:v{{ .Major }}.{{ .Minor }}-amd64"
    - "ghcr.io/heliumdiy/lightweight-dashboard:latest-amd64"
    - "ghcr.io/heliumdiy/lightweight-dashboard:latest"
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/heliumdiy/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/heliumdiy/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
  -
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
    - "ghcr.io/heliumdiy/lightweight-dashboard:v{{ .Tag }}-arm64"
    - "ghcr.io/heliumdiy/lightweight-dashboard:v{{ .Major }}-arm64"
    - "ghcr.io/heliumdiy/lightweight-dashboard:v{{ .Major }}.{{ .Minor }}-arm64"
    - "ghcr.io/heliumdiy/lightweight-dashboard:latest-arm64"
    - "ghcr.io/heliumdiy/lightweight-dashboard:latest"
    build_flag_templates:
    - --platform=linux/arm64/v8
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/heliumdiy/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/heliumdiy/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
docker_manifests:
- name_template: ghcr.io/heliumdiy/{{ .ProjectName }}:v{{ .Tag }}
  image_templates:
  - "ghcr.io/heliumdiy/lightweight-dashboard:v{{ .Tag }}-amd64"
  - "ghcr.io/heliumdiy/lightweight-dashboard:v{{ .Major }}-amd64"
  - "ghcr.io/heliumdiy/lightweight-dashboard:v{{ .Major }}.{{ .Minor }}-amd64"
  - "ghcr.io/heliumdiy/lightweight-dashboard:latest-amd64"
  - "ghcr.io/heliumdiy/lightweight-dashboard:v{{ .Tag }}-arm64"
  - "ghcr.io/heliumdiy/lightweight-dashboard:v{{ .Major }}-arm64"
  - "ghcr.io/heliumdiy/lightweight-dashboard:v{{ .Major }}.{{ .Minor }}-arm64"
  - "ghcr.io/heliumdiy/lightweight-dashboard:latest-arm64"
docker_signs:
  - cmd: cosign
    env:
    - COSIGN_EXPERIMENTAL=1
    artifacts: images
    output: true
    args:
    - 'sign'
    - '${artifact}'